#[build]
[target.'cfg(any(target_arch = "x86", target_arch = "x86_64"))']
rustflags = ["-C", "target-feature=+sse2,+sse3,+sse4.1,+ssse3,+avx,+avx2"]

[target.'cfg(target_arch = "aarch64")']
#rustflags = ["-C", "target-feature=+neon"]
